name: Example - Use OAuth Tokens

on:
  workflow_dispatch:

jobs:
  use-oauth-tokens:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
        
      - name: Restore Claude credentials from cache
        id: restore-creds
        uses: actions/cache/restore@v3
        with:
          path: credentials.json
          key: claude-credentials-${{ github.sha }}
          restore-keys: |
            claude-credentials-
            
      - name: Check and refresh token if needed
        id: refresh-token
        run: |
          if [ -f credentials.json ]; then
            echo "✅ Claude credentials found in cache"
            
            # Refresh token if needed
            chmod +x .github/scripts/claude_token_refresh.rb
            .github/scripts/claude_token_refresh.rb
            
            echo "## ✅ Token Status" >> $GITHUB_STEP_SUMMARY
            echo "Tokens are ready for use." >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ No Claude credentials found in cache"
            echo "## ❌ No Credentials Found" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please run the 'Claude OAuth Login' workflow first." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "[Run Claude OAuth Login](${{ github.server_url }}/${{ github.repository }}/actions/workflows/claude-oauth-login.yml)" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          
      - name: Use tokens (example)
        run: |
          echo "Access Token: ${{ steps.refresh-token.outputs.access_token }}"
          echo "Refresh Token: ${{ steps.refresh-token.outputs.refresh_token }}"
          echo "Expires At: ${{ steps.refresh-token.outputs.expires_at }}"
          
          echo "## Token Information" >> $GITHUB_STEP_SUMMARY
          echo "- Access token available: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Refresh token available: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Expires at: $(date -d @$((${{ steps.refresh-token.outputs.expires_at }}/1000)))" >> $GITHUB_STEP_SUMMARY